--추천 테이블
CREATE TABLE THUMB(
	T_ID NVARCHAR2(20) ,
	T_NUM NUMBER
);
--기본키 설정
ALTER TABLE THUMB 
ADD CONSTRAINT PK_T_ID_T_NUM PRIMARY KEY(T_ID, T_NUM);

--외래키 설정
ALTER TABLE THUMB
ADD CONSTRAINTS FK_THUMB_T_NUM FOREIGN KEY(T_NUM) REFERENCES BOARD(B_NUM) 
ON DELETE CASCADE;

--원글 게시판
CREATE TABLE BOARD(
    B_NUM NUMBER NOT NULL, --PK
    B_TITLE NVARCHAR2(50) NOT NULL,
    B_CONTENTS NCLOB NOT NULL, --글내용을 문자 무한대
    B_ID NVARCHAR2(20) NOT NULL, 
    B_DATE DATE DEFAULT SYSDATE,
    B_VIEWS NUMBER DEFAULT 0 NOT NULL,
    B_THUMBS NUMBER DEFAULT 0
    
);
INSERT INTO B
VALUES(BOARD_SEQ.NEXTVAL,'게시글40','무궁화꽃이 피었습니다.','2083004643',DEFAULT,DEFAULT,DEFAULT);

COMMIT;

SELECT * FROM B;


--기본키
ALTER TABLE BOARD 
ADD CONSTRAINT PK_B_NUM PRIMARY KEY(B_NUM);


CREATE SEQUENCE BOARD_SEQ; -- 1부터 1씩증가
CREATE SYNONYM B FOR BOARD;

--답글 게시판
CREATE TABLE REPLY(
    R_NUM NUMBER NOT NULL, --PK
    R_BNUM NUMBER NOT NULL, --FK, 부모(B)테이블의 B_NUM을 참조
    R_CONTENTS NVARCHAR2(200) NOT NULL,
    R_ID NVARCHAR2(20) NOT NULL, --FK, 부모(M)테이블의 M_ID 참조
    R_DATE DATE DEFAULT SYSDATE NOT NULL
 );
 CREATE SEQUENCE REPLY_SEQ;
 CREATE SYNONYM R FOR REPLY;

--기본키
ALTER TABLE REPLY 
ADD CONSTRAINT PK_R_NUM PRIMARY KEY(R_NUM);
--외래키
ALTER TABLE REPLY
ADD CONSTRAINT FK_R_BNUM FOREIGN KEY(R_BNUM)
REFERENCES BOARD(B_NUM); -- ON DELETE CASCASE; (트랜잭션으로 처리하기 위해 제외)


--최신글순으로 원글 출력 VIEW
CREATE OR REPLACE VIEW BLIST AS
SELECT B.B_NUM,    --BNUM:빈 필드명과 컬럼명이 일치할수 없다면 알리아스로 맞춘다 
       B.B_TITLE,
       B.B_CONTENTS,
       B.B_ID,
       B.B_DATE,
       B.B_VIEWS 
FROM B
ORDER BY B.B_DATE DESC;

SELECT ROWNUM, BLIST.* FROM BLIST;

CREATE OR REPLACE VIEW BLIST_1 AS
SELECT ROWNUM AS RONUM, BLIST.*
FROM BLIST;

SELECT * FROM BLIST_1;

--파일 업로드 테이블 추가할 것(1:N)
CREATE TABLE BOARDFILE(
    BF_NUM NUMBER NOT NULL, 
    BF_BNUM NUMBER NOT NULL, --FK
    BF_ORINAME NVARCHAR2(50) NOT NULL,
    BF_SYSNAME NVARCHAR2(50) NOT NULL
);
CREATE SYNONYM BF FOR BOARDFILE;
CREATE SEQUENCE BF_SEQ;
--기본키
ALTER TABLE BOARDFILE 
ADD CONSTRAINT PK_BF_NUM PRIMARY KEY(BF_NUM);
--외래키
ALTER TABLE BOARDFILE
ADD CONSTRAINT FK_BF_BNUM FOREIGN KEY(BF_BNUM)
REFERENCES BOARD(B_NUM);

COMMIT;

